name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # Midnight daily
  workflow_dispatch:      # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: bhavya-data-analysis
          outputs: dist/github-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Snake Output
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/"
          message: "Generated snake animation"
